---
title: "LetterOfPresentation"
author: "Collin Schwantes"
date: "10/7/2019"
output:
  word_document: default
  html_document: default
---


Dear Dr. Poisot,

I was introduced to your work by various colleagues who use networks to investigate ecological processes. While my background is firmly as a "dirty boots" ecologist who studies species distributions in agroecosytems, I developed a deep appreciation of and interest in theoretical ecology while studying my masters degree. During my PhD studies, I would like to apply machine learning to graph representations of empirical ecological interactions in order to derive ecological theory. Specifically, I am deeply interested in understanding the relationship between fine scale behavioral interactions and landscape scale species distribitution patterns. 

My career in ecology began in 2007 working as a field technician conducting habitat restoration in prairies in Southeastern Wisconsin. There I learned how to delianate wetlands using plant species, plant native plants, identify and remove invasive species and plan field research. 

In Claudio Gratton's lab at the University of Wisconsin Madison, I was able to grow from a labratory techinician to a field work team lead and co-lab manager while conducting research in agroecosystems and analyzing nutrient flow around lake Myvtan in Iceland. During that time I was responsible for executing the entire data collection pipeline from field sampling to data entry on five projects. As a team lead, I was responsbile for creating training materials for athropods, flowering plants, lab equipment, lab safety, data entry and basic GIS techniques that were critical to the lab. I also had the pleasure of training six undergraduate technicians on field and lab techniques as well as several graduate students on using ArcGIS. In my role as techincal support, I directly contributed data to **X** number of research of papers and dissertations. Several of those papers were included in meta-data analyses regarding ecosystem services and landscape composition **see claudios lab website**.

At the University of Colorado-Boulder, Dr. Deane Bowers gave me the opportunity to contribute to a multi-institution research initiative and develop an additional research project during my Masters degree. The overarching theme of our USDA-NIFA funded project was the investigation of biofuel policy's impacts on native bee communities in the grasslands of Eastern Colorado. On this project, I used my past experience in pollinator diversity studies to help design and execute collection methods for grassland bees. Because this area was extremely under represented in physical and digitized in museum collections, we needed to conduct extensive literature review to understand what level of species diversity to expect. This lead me to build a tool that scrapes the Biodiversity Heritage Library and the Discovery Life websites in order to build natural history tables for each of our expected bee species. Using these natural history tables in combination with other literature, we were able to develop lists of floral associations, bee body size, and sociality, all potentially important traits for explaining community composition. For my thesis, I examined the relationship between landscape elements and species community composition at various spatial scales using multivariate generalized linear models. I found three  components of the landscape (topography, row crops, roadside edge) explained differences in communinity composition at distinct spatial scales. The impact of roadside edges was particularly interesting because they occur on a fine scale that concentrate floral resources in narrow bands leading to a high number of species interactions. To investigate these interactions further, I established a common garden experiment planted in Helianthus petiolarus, an abundant roadside plant, where I artifically increased the concentration of a cryptic predator and monitored foraging behavior in solitary bees. I found that the predators had no detectable effect on foraging behavior, a direct contrast to previous studies of cryptic predators conducted in eusocial bees. 

After completing my masters, I began working on a project with the University of Colorado Musuem of Natural History Bee's Needs participatory science project where I developed a data dashboard for volunteers and designed analyses to investigate trends in cavity nesting insect diversity. One of the goals of this short project was to develop a statistical model that would assist in identification of the cavity nesting organisms based on nest characteristics and nest box location. Unfortunately, the data were not sufficient to develop an identification model. However, I was successful in deploying an Rshiny appclication that allowed users to access their data and explore it as they saw fit. 

In my next position, I spent six months as an intern in the Smithsonian Institute's National Museum of Natural History working in the National Insect Collection imaging  primary type specimens of parasitic wasps and developing an online hymenoptera anatomy learning tool. During this time, I gained a deep appreciation for the amount of manual labor it takes to make collections accessible digitally. To help ease the burden of data entry, I wrote a python application that automated much of the tidious file management and data re-entry involved in processing specimens As a result of this work, we were able to make high quality annotated images of rapidly deterioting holotype and lectotype specimens and disseminate them via a publicly accessible web portal.  

I then joined the consulting firm Accenture Federal Services where I worked as a Biosurveillance Scientist at the National Biosurveillance Integration Center (NBIC), part of the Office of Health Affairs in the Department of Homeland Security. NBIC's mission is to use open source information to monitor the globe for emerging infectious diseases, invasive species, or other biological threats to animals, plants, and people, and share the information with interagency partners. The pace of production at NBIC is a demanding three reports per day plus as-needed in depth products. This reporting cycle meant that I had to hone my analytical and research skills to be as efficient as possible while still delivering a high quality products at an audience appropriate level. As the sole ecologist employed by NBIC, it fell to me to push my co-workers to think about systems as dynamic entities and dissuade them from an anthropocentric view of biology. Because of my previous experience working with digital collections, historical literature, and open source geospatial information, I was able to greatly expand the types of information used to contextualize events of concern. This became extremely important during the Zika outbreak in Latin America. I was able to provide finer scale habitat suitability maps for disease vectors to local public health officials so they could make informed decisions about transmission risk. Addtionally, I wrote several reports dispelling frequently repeated falsehoods about health issues among migrant populations including an in depth document on cholera that received praise from colleagues at the US Centers for Disease Control and Prevention. 








At NBIC, I was responsible for delivering three reports daily and in depth reports as needed. This demanding reporting cycle meant that I had to hone my analytical and research skills to be as efficient as possible while still delivering a high quality product. 







Deane's guidance on study design, excellent mentorship model, obvious care for her students

Kendi Davies community ecology class






outlining past research achievements,
- university of wisconsin madison research tech
  - developed strong foundations in field research, agroecology, understand how data are collected, curated, and stored   
- university of Colorado 
   - Behavioral ecology, pollinator predator interactions
   - community ecology - species distribution models
   - spatial modeling
 - smithsonian
    - deeper appreciation for specimen curation
    - saw the need for better use of 
  - NBIC
    - how academic research is translated into govt policy, importance of clear concise sci commm., value of data vizualization, recognize the value of openscience to resource constrained govt institutions like public health and wildlife mgmt agencies

future research plans,
- explore the relationship between species interaction networks and spatial scale in ecology.
  - establish online repository of interaction data and tools to increase accessibility to network analysis
    - build NLP tool to extract interaction data from historical literature
  - understand how inter-species interactions impact community composition
  - understand community resiliency and its relationship to network structure 
    - Leverage open data from GBIF etc - Use AI to explore relationships between interaction and spatial scale in communities
  - demonstrate the need for additional natural history/biodiversity project using maths



