---
title: "Open Science"
author: "Collin Schwantes"
date: "9/29/2019"
output: html_document
---

A statement on Open Science of up to 400 words, if possible including quantified or qualified statements about previous or ongoing open practices, or a statement of open philosophy for applicants who have not received the opportunity of working openly

Open science 
improves research outcomes through:
increases access - increasing spread of ideas
allows for replication and thus verification of results, 
makes researchers more efficient and better collaborators
builds community
science as service


Everyday we see the world, but how we make sense of it depends on our context. Science seeks to understand the universe through rigorous testing and observation. Open science lays knowledge and process bare. It incentivises altruistic behaviors, fosters benevolent research communities, and increases access.     


I have been fortunate to have had several mentors, Kaitlin Stack Whitney, Max Joesph, and Tim Mehaan, throughout my career who have pushed open science and demonstrated its power to generate knowledge and a benevolent research culture. Kaitlin championed the recognition of research technician's work in lab publications and provided paid time to read the literature underlying the research we were conducting. Max created a safe space where his fellow graduate students could present their early explorations of a particular quantitative method or ask for support in a low pressure environment. Tim introduced me to the world of open data and open software while I was a research technician and I have never looked back.       

In my current role as a Biosurveillance Scientist, I have pushed the National Biosurveillance Integration Center to adapt reproducible workflows using open source tools and establish an open science culture. Not only do we produce higher quality work, we have created an environment that fosters intellectual and technical growth. 
-- how much you like teaching others and how much you learn from having to document and share code.      

Open science removes unnecessary barriers to research and improves research outcomes by ensuring those with the best ideas have access to data (where appropriate) and tools. 



During my graduate work at the University of Colorado-Boulder, I had a wonderful colleague named Max Joesph who pushed me to use open science practices. 

In undergrad - Dr. Tim Mehaan first introduced me to Moth Tools - a collection of python scripts used for landscape analysis 

Dr. Kaitlin Stack Whitney showed me what a mentor advocate looks like and how 

Graduate work using GBIF 

Smithsonian wasp catalog

Mosquito App

Thesis

R

Git
 
Python

Current position supporting open science at NBIC


Science seeks to understand the universe through rigorous testing and observation.
Open science lays knowledge and process bare as much as ethically possible. It incentivises altruistic behaviors, fosters benevolent research communities, and increases access. This connects the lab to the world, creating a flow of ideas and values that improve both.

Open science bakes reproducibility into the research process by giving access to data (where appropriate) and tools. Workflows that emphasize reproducibility make researchers more efficient in the long term because they must think collaboratively, even if their only collaborator is their future self. Collaborative thinking encourages organization, documentation, and careful consideration of assumptions as you attempt to explain your process and data to others. There now exist a plethora of open platforms for sharing both data and tools that facilite reproducible research methodologies. 

In my current role as a Biosurveillance Scientist, I have pushed the National Biosurveillance Integration Center to adopt reproducible workflows using open source tools and establish an open science culture. Not only do we produce higher quality work more efficiently using modular R scripts, we have created an environment that fosters intellectual and technical growth. This would not have been possible without teaching materials from Jenny Bryan and Hadley Wickham, and the example set by my open science mentors.

I have been fortunate to have had several mentors throughout my career who pushed open science and demonstrated its power to generate knowledge and a benevolent research culture. Tim Meehan introduced me to the world of open data and open software while I was a research technician, showing me the power of these approaches to generate insight. Kaitlin Whitney Stack championed the recognition of research technician's work in lab publications, ensuring everyone’s contributions were recognized. Max Joseph created a safe space where his fellow graduate students could present their early explorations of a particular quantitative method or ask for support in a low pressure environment, all while gently nudging us towards git proficiency. 

In order to be of service to broader communities, I developed a participatory ("citizen") science dashboard with the University of Colorado, contributed to an open repository of research grade holotype images at the Smithsonian, and a built a graphical user interface for a mosquito control model with the University of Maryland. Each of these endeavors sought to freely share knowledge, including code, outside the lab and academia. 

Open science removes unnecessary barriers to research and improves outcomes by creating supportive and inclusive environments where access to tools and data are not limited by funding or other factors. Having benefited from and fostered open science culture, I have experienced first hand the value it creates from technical, intellilectual, and personal perspectives. As a member of the Poisot lab, I would actively cultivate open science practices with the hope of benefiting my labmates, collaborators, and community.





